pais(alemania).
pais(francia).
pais(belgica).
pais(italia).
pais(espana).
pais(paises_bajos).
pais(suiza).
pais(luxemburgo).
pais(austria).

adyacentes(pais(alemania),pais(belgica)).
adyacentes(pais(alemania),pais(francia)).
adyacentes(pais(alemania),pais(suiza)).
adyacentes(pais(alemania),pais(luxemburgo)).
adyacentes(pais(alemania),pais(paises_bajos)).
adyacentes(pais(alemania),pais(austria)).
adyacentes(pais(francia),pais(italia)).
adyacentes(pais(francia),pais(espana)).
adyacentes(pais(francia),pais(belgica)).
adyacentes(pais(francia),pais(suiza)).
adyacentes(pais(francia),pais(luxemburgo)).
adyacentes(pais(belgica),pais(luxemburgo)).
adyacentes(pais(belgica),pais(paises_bajos)).
adyacentes(pais(italia),pais(suiza)).
adyacentes(pais(italia),pais(austria)).
adyacentes(pais(italia),pais(suiza)).
adyacentes(pais(suiza),pais(austria)).

color(rosa).
color(verde).
color(negro).
color(azul).
color(amarillo).
color(morado).
